name: Build iOS reusable workflow

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string
      flutter_version:
        required: true
        type: string

jobs:
  build-ios:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v2
      - run: git branch

      - name: Add build number to env
        run: echo "IOS_BUILD_NUMBER=${{ inputs.build_number }}" >> $GITHUB_ENV
      
      - name: echo vars
        run: |
          echo ${{ inputs.build_number }}
          echo ${{ inputs.flutter_version }}
          echo $IOS_BUILD_NUMBER

      - name: echo secret from this repo
        run: |
          echo "$((${{ secrets.TEST_ACTION_BUILD_VERSION }}+1))"
