name: Build Android reusable workflow

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string
      flutter_version:
        required: true
        type: string
    outputs:
      success:
        value: ${{ jobs.build_android.outputs.success }}

jobs:
  build_android:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.set_job_status_step.outputs.build_successful }}
    steps:        
      - uses: actions/checkout@v2
      - run: git branch
      
      - name: echo vars
        run: |
          echo ${{ inputs.build_number }}
          echo ${{ inputs.flutter_version }}

      - name: echo secret from this repo
        run: |
          echo "$((${{ secrets.TEST_ACTION_BUILD_VERSION }}+1))"

      # - name: Try to fail
      #   run: exit 1

      - name: Set build_successful output
        id: set_job_status_step
        if: ${{ success() }}
        run: echo "::set-output name=build_successful::true"