name: Build iOS reusable workflow

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string
      flutter_version:
        required: true
        type: string
    outputs:
      success:
        value: ${{ jobs.build-ios.outputs.success }}

jobs:
  build-ios:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.set_job_status_step.outputs.build_successful }}
    steps:        
      - uses: actions/checkout@v2
      - run: git branch

      - name: Add build number to env
        run: echo "IOS_BUILD_NUMBER=${{ inputs.build_number }}" >> $GITHUB_ENV
      
      - name: echo vars
        run: |
          echo ${{ inputs.build_number }}
          echo ${{ inputs.flutter_version }}
          echo $IOS_BUILD_NUMBER

      - name: echo secret from this repo
        run: |
          echo "$((${{ secrets.TEST_ACTION_BUILD_VERSION }}+1))"

      - name: Try to fail
        run: exit 1
      
      - name: Set build_successful output
        id: set_job_status_step
        if: ${{ success() }}
        run: echo "::set-output name=build_successful::true"
