name: Build for 2 platform

on:
  workflow_dispatch:
    inputs:
      BUILD_NUMBER:
        description: The build number used in app version
        required: true
  workflow_run:
    workflows: [Test and trigger build Android and iOS]
    types:
      - completed

jobs:
  platform_2:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == null }}
    steps:        
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch

      - name: Set build var from workflow run number
        if: ${{ github.event.workflow_run.run_number != null }}
        env:
          RUN_NUMBER: ${{ github.event.workflow_run.run_number }}
        run: echo "BUILD_NUMBER=$(($RUN_NUMBER+1000))" >> $GITHUB_ENV
      
      - name: Set build var from input number
        if: ${{ github.event.workflow_run.run_number == null }}
        run: echo "BUILD_NUMBER=${{ github.event.inputs.build_number }}" >> $GITHUB_ENV
      
      - name: echo vars
        run: |
          echo $BUILD_NUMBER
          echo ${{ github.event.workflow_run.head_branch || github.ref_name }}
