name: Build for 2 platform

on:
  workflow_dispatch:
    inputs:
      BUILD_NUMBER:
        description: The build number used in app version
        required: true
  workflow_run:
    workflows: [Test and trigger build Android and iOS]
    types:
      - completed

jobs:
  platform_2:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == null }}
    steps:        
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - name: Echo workflow number
        run: |
          echo ${{ (github.event.workflow_run.run_number || github.event.inputs.build_number) + 1000 }}
          echo ${{ github.event.workflow_run.head_branch || github.ref_name }}
