name: Build for 1 platform

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string

jobs:
  platform_1:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      
      - name: echo vars
        run: |
          echo ${{ inputs.build_number }}
          echo ${{ github.event.workflow_run.head_branch || github.ref_name }}
