name: "Test and trigger build Android and iOS"

on:
  workflow_dispatch:
    inputs:
      build_os:
        description: Deploy iOS internal build
        required: true 
        type: boolean
      build_android:
        description: Deploy Android internal build
        required: true 
        type: boolean 
  push:
    branches:
      - main 
      - develop
      - feature/*
      - hotfix/*

env:
  flutter_version: "2.10.5"

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.set-output-build-number.outputs.build_number }}
    steps:
      - uses: actions/checkout@v2.1.0
      # - uses: subosito/flutter-action@v1.5.3
      #   with:
      #     channel: "stable"
      #     flutter-version: ${{ env.flutter_version }}
      # - name: Run static analysis
      #   run: flutter analyze
      # - name: Run unit tests
      #   run: flutter test --coverage
      # - name: Very Good Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v1.2.1
      #   with:
      #     min_coverage: 90
      - name: Autoincrement a new build version
        run: |
          echo "NEW_BUILD_VERSION=$((${{ secrets.TEST_ACTION_BUILD_VERSION }}+1))" >> $GITHUB_ENV
      - name: Update build version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TEST_ACTION_BUILD_VERSION'
          value: ${{ env.NEW_BUILD_VERSION }}
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: set outputs with build number
        id: set-output-build-number
        run: |    
          # If workflow_dispatch, use inputs (left), if other trigger, use default env (right)
          echo "::set-output name=build_number::${{ env.NEW_BUILD_VERSION }}"
      # Notify only if test fails. If not, build workflows will be triggered normally
      - name: Echo action
        if: ${{ failure() }}
        env:
          MESSAGE_ACTIONS: '[{ "@type": "OpenUri", "name": "View Commit", "targets": [{ "os": "default", "uri": "${{ github.event.head_commit.url }}" }] }]'
        run: echo "$MESSAGE_ACTIONS"
      - name: Echo again
        if: ${{ failure() }}
        run: echo "Latest push to ${{ github.ref_name }} failed to pass CI."
  
  echo-build-number:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: echo vars
        run: |
          echo ${{ needs.test.outputs.build_number }}
          echo ${{ github.ref_name }}

  call-build-ios-workflow:
    needs: [test]
    uses: ./.github/workflows/build_ios.yml
    with:
      build_number: ${{ needs.test.outputs.build_number }}
      branch_name: ${{ github.ref_name }}
    secrets: inherit

  call-build-android-workflow:
    needs: [test]
    uses: ./.github/workflows/build_android.yml
    with:
      build_number: ${{ needs.test.outputs.build_number }}
      branch_name: ${{ github.ref_name }}
    secrets: inherit
